apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  SECRET_KEY: amtiZmFsYmVpYWZieWl2cGZ5YTc2MHF1ODJxM3I3MnA5cXIycjdqOGc=
  DEBUG: MQ==
  DJANGO_ALLOWED_HOSTS: KiIqCg==
  DB_USER: cm9vdA==
  DB_PASSWORD: cm9vdA==
  DB_NAME: d2FycHNoYXJl
  DB_HOST: bG9jYWxob3N0
  DB_PORT: MzMwNg==
  AWS_ACCESS_KEY_ID: RE8wMEJUODdXTlJLSFg4R1BGUUM=
  AWS_SECRET_ACCESS_KEY: U29iS2Q5YzVxdDhuNFI5MGkyWWRubEUxd05Pc2Rya2Q3RmxX
  AWS_STORAGE_BUCKET_NAME: d2FycC1zaGFyZQ==
  AWS_ENDPOINT_URL: aHR0cHM6Ly9mcmExLmRpZ2l0YWxvY2VzcGFjZXMubmV0
  AWS_STORAGE_BUCKET_URL: aHR0cHM6Ly93YXJwLXNoYXJlLmZyYTEuZGlnaXRhbG9jYXNwYWNlcy5jb20=
